baseurl = "http://nimahejazi.org/blog/"
languageCode = "en-us"
title = "Almost Surely..."
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
enableEmoji = true
disqusShortname = "nhejazi"
googleAnalytics = "UA-67244126-3"
MathJaxCDN = "https://cdn.bootcss.com"
MathJaxVersion = "2.7.1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author               = "Nima Hejazi"
    # Sets the meta tag description, usually reserved for the main page
    description          = "Nima's musings on statistics and modern science"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Almost Surely..."
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/post/" # NOTE: does not respect baseURL

    # Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = true
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    customCSS            = ["/css/main.min.css"]
    customJS             = ["/js/main.min.js"]

    # parms.intro will appear on the sidebar
    # This is optional, but it's suggested to use
[params.intro]
    header    = "Almost Surely..."
    paragraph = "musings on statistics and science by Nima Hejazi"
    about     = "Nima is a Biostatistics PhD student. His interests center around causal inference, nonparametric statistics and machine learning, and statistical computing, with applications in the biomedical sciences."

    # This will also appear on the sidebar.
    # A width of less than 100px is recommended
    # This is optional
[params.intro.pic]
    src       = "/img/main/avatar.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = ""

    # Adjust the amount of recent posts on the sidebar.
    # This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 4

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "Posts"
    url = "/post"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    identifier = "fa fa-list"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    identifier = "fa fa-info"
    weight = 3

[[menu.main]]
    name = "CV"
    url = "https://www.stat.berkeley.edu/~nhejazi/hejazi-cv.pdf"
    identifier = "fa fa-user"
    weight = 4

[[menu.main]]
    name = "Main"
    url = "http://nimahejazi.org"
    identifier = "fa fa-reply"
    weight = 5

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "nhejazi"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "nshejazi"
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "nshejazi"
    slideshare      = ""
    stackoverflow   = "nhejazi"
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "nima.hejazi"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "nshejazi"
    email           = "nh@nimahejazi.org"

