baseURL = "https://almost-surely.netlify.com/"
languageCode = "en-us"
title = "Almost Surely?"
theme = "hugo-kiss"
copyright = "&copy; <a href=\"https://nimahejazi.org\">Nima Hejazi</a> 2017-2021"
disqusShortname = "nhejazi"
googleAnalytics = "UA-67244126-3"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Nima Hejazi" # Author full name
authorEmail = "nh@nimahejazi.org" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Stochastic Musings on Statistics, Software, and Science" # homepage title
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

[params.features]
disqusOnDemand = true  # Load Disqus comments on click

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "nshejazi"
github = "nhejazi"
email = "nh@nimahejazi.org"
linkedin = "nshejazi"
facebook = ""
instagram = ""
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","twitter","instagram","linkedin","email"]

[params.sections_left]
"/about" = "This blog is about..."
#"https://example.com" = "Example"

[params.sections_right]
"https://nimahejazi.org" = "Nima's homepage"

[params.matomoAnalytics]
siteID = 1
rootURL = ""

[params.fathomAnalytics]
rootURL = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
